In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

pd.set_option('display.max_columns', None)

print(f'Verificar que el flights_2022_es exista...')
if not os.path.exists('flights_2022_es.csv'):
    raise Exception("El csv flights_2022_es.csv no existe. Se interrumpe el notebook")

print(f'flights_2022_es.csv encontrado!')

df = pd.read_csv('flights_2022_es.csv')

Verificar que el flights_2022_es exista...
flights_2022_es.csv encontrado!

In [2]:
df_2022 = df
print(df.shape)
df.head(5)

(687860, 32)

,fecha_vuelo,aerolinea,aerolinea_dot,codigo_aerolinea,codigo_dot,numero_vuelo,origen,ciudad_origen,destino,ciudad_destino,hora_salida_programada,hora_salida_real,retraso_salida,tiempo_rodaje_salida,despegue,aterrizaje,tiempo_rodaje_llegada,hora_llegada_programada,hora_llegada_real,retraso_llegada,cancelado,codigo_cancelacion,desviado,duracion_programada,duracion_real,tiempo_en_aire,distancia,retraso_por_aerolinea,retraso_por_clima,retraso_por_trafico_aereo,retraso_por_seguridad,retraso_por_avion_tardio
0,2022-11-19,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,1149,MSP,"Minneapolis, MN",SEA,"Seattle, WA",2120,2114.0,-6.0,9.0,2123.0,2232.0,38.0,2315,2310.0,-5.0,0.0,NaN,0.0,235.0,236.0,189.0,1399.0,NaN,NaN,NaN,NaN,NaN
1,2022-07-22,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,459,DEN,"Denver, CO",MSP,"Minneapolis, MN",954,1000.0,6.0,20.0,1020.0,1247.0,5.0,1252,1252.0,0.0,0.0,NaN,0.0,118.0,112.0,87.0,680.0,NaN,NaN,NaN,NaN,NaN
2,2022-05-01,Southwest Airlines Co.,Southwest Airlines Co.: WN,WN,19393,1011,BWI,"Baltimore, MD",BDL,"Hartford, CT",1735,1738.0,3.0,12.0,1750.0,1843.0,3.0,1840,1846.0,6.0,0.0,NaN,0.0,65.0,68.0,53.0,283.0,NaN,NaN,NaN,NaN,NaN
3,2022-05-05,JetBlue Airways,JetBlue Airways: B6,B6,20409,1273,JFK,"New York, NY",CHS,"Charleston, SC",803,800.0,-3.0,17.0,817.0,943.0,3.0,1012,946.0,-26.0,0.0,NaN,0.0,129.0,106.0,86.0,636.0,NaN,NaN,NaN,NaN,NaN
4,2022-11-12,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2706,GRR,"Grand Rapids, MI",MSP,"Minneapolis, MN",730,720.0,-10.0,10.0,730.0,731.0,5.0,806,736.0,-30.0,0.0,NaN,0.0,96.0,76.0,61.0,408.0,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 687860 entries, 0 to 687859
Data columns (total 32 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   fecha_vuelo                687860 non-null  object
 1   aerolinea                  687860 non-null  object
 2   aerolinea_dot              687860 non-null  object
 3   codigo_aerolinea           687860 non-null  object
 4   codigo_dot                 687860 non-null  int64
 5   numero_vuelo               687860 non-null  int64
 6   origen                     687860 non-null  object
 7   ciudad_origen              687860 non-null  object
 8   destino                    687860 non-null  object
 9   ciudad_destino             687860 non-null  object
 10  hora_salida_programada     687860 non-null  int64
 11  hora_salida_real           669844 non-null  float64
 12  retraso_salida             669839 non-null  float64
 13  tiempo_rodaje_salida       669506 non-null  float64
 14  despegue                   669506 non-null  float64
 15  aterrizaje                 669235 non-null  float64
 16  tiempo_rodaje_llegada      669235 non-null  float64
 17  hora_llegada_programada    687860 non-null  int64
 18  hora_llegada_real          669236 non-null  float64
 19  retraso_llegada            667761 non-null  float64
 20  cancelado                  687860 non-null  float64
 21  codigo_cancelacion         18448 non-null   object
 22  desviado                   687860 non-null  float64
 23  duracion_programada        687860 non-null  float64
 24  duracion_real              667761 non-null  float64
 25  tiempo_en_aire             667761 non-null  float64
 26  distancia                  687860 non-null  float64
 27  retraso_por_aerolinea      140468 non-null  float64
 28  retraso_por_clima          140468 non-null  float64
 29  retraso_por_trafico_aereo  140468 non-null  float64
 30  retraso_por_seguridad      140468 non-null  float64
 31  retraso_por_avion_tardio   140468 non-null  float64
dtypes: float64(19), int64(4), object(9)
memory usage: 167.9+ MB

In [4]:
df.nunique()

fecha_vuelo                   365
aerolinea                      17
aerolinea_dot                  17
codigo_aerolinea               17
codigo_dot                     17
numero_vuelo                 6594
origen                        370
ciudad_origen                 364
destino                       370
ciudad_destino                364
hora_salida_programada       1293
hora_salida_real             1431
retraso_salida               1136
tiempo_rodaje_salida          171
despegue                     1432
aterrizaje                   1440
tiempo_rodaje_llegada         167
hora_llegada_programada      1386
hora_llegada_real            1440
retraso_llegada              1167
cancelado                       2
codigo_cancelacion              4
desviado                        2
duracion_programada           566
duracion_real                 660
tiempo_en_aire                632
distancia                    1590
retraso_por_aerolinea         935
retraso_por_clima             451
retraso_por_trafico_aereo     383
retraso_por_seguridad         107
retraso_por_avion_tardio      641
dtype: int64

### Variables Temporales
1. Se agrega la variable del mes

In [5]:
df_2022['fecha_vuelo'] = pd.to_datetime(df_2022['fecha_vuelo'])
df_2022['mes'] = df_2022['fecha_vuelo'].dt.month

print(f"Filas cargadas: {len(df_2022)}")
print('mes' in df_2022.columns)  # debería dar True

Filas cargadas: 687860
True

Nos quedamos con el 25% de registros de cada mes de manera aleatoria. Agregamos un random_state para que nos de siempre la misma muestra de datos. El dataset es muy grande entonces necesitamos reducirlo para que no lleve tanto tiempo correr las APIs y luego quizás el modelo.

In [6]:
df_2022 = df_2022.groupby('mes', group_keys=False).apply(
    lambda x: x.sample(frac=0.25, random_state=42)
)

print(f"Filas después de la muestra: {len(df_2022)}")

Filas después de la muestra: 171966

C:\Users\aaron\AppData\Local\Temp\ipykernel_17800\1385801954.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_2022 = df_2022.groupby('mes', group_keys=False).apply(

Filtramos por aeropuertos más importantes.

In [7]:
top_aeropuertos = df_2022['origen'].value_counts()
cobertura = top_aeropuertos.cumsum() / top_aeropuertos.sum()
aeropuertos_relevantes = cobertura[cobertura <= 0.90].index.tolist()

df_2022 = df_2022[df_2022['origen'].isin(aeropuertos_relevantes)]

print(f"Filas después de filtrar aeropuertos: {len(df_2022)}")
print(f"Cantidad de aeropuertos relevantes: {len(aeropuertos_relevantes)}")

Filas después de filtrar aeropuertos: 154586
Cantidad de aeropuertos relevantes: 92

Creamos la variable target para despues predecir

In [8]:
df_2022['retrasado'] = (df_2022['retraso_salida'] > 15).astype(int)

print(df_2022['retrasado'].value_counts())

retrasado
0    123038
1     31548
Name: count, dtype: int64

Hacemos un llamado a una API para obtener la longitud y latitud de cada aeropuerto.

In [9]:
import requests

airports_db = pd.read_csv("https://ourairports.com/data/airports.csv")
airports_db = airports_db[airports_db['iata_code'].isin(aeropuertos_relevantes)]
airports_db = airports_db[['iata_code', 'latitude_deg', 'longitude_deg']].dropna()
airports_db = airports_db.rename(columns={'iata_code': 'origen', 'latitude_deg': 'lat', 'longitude_deg': 'lon'})

print(f"Aeropuertos con coordenadas encontradas: {len(airports_db)}")
airports_db.head()

Aeropuertos con coordenadas encontradas: 92

      origen        lat         lon
38564    ABQ  35.039976 -106.608925
38624    ALB  42.748299  -73.801697
38684    ATL  33.636700  -84.428101
38693    AUS  30.197535  -97.662015
38740    BDL  41.938555  -72.688016

Con esa longitud y latitud que conseguimos, podemos obtener el clima de los registros que pertencen a nuestra dataset, en determinado momento en el aeropuerto de origen.

In [10]:
import time

def clima_por_aeropuerto():
    clima_data = []

    for i, row in airports_db.iterrows():
        try:
            response = requests.get(
                "https://archive-api.open-meteo.com/v1/archive",
                params={
                    "latitude": row['lat'],
                    "longitude": row['lon'],
                    "start_date": "2022-01-01",
                    "end_date": "2022-12-31",
                    "daily": "temperature_2m_mean,precipitation_sum,windspeed_10m_max",
                    "timezone": "America/New_York"
                },
                timeout=30
            )
            data = response.json()
            temp = pd.DataFrame({
                'fecha_vuelo': data['daily']['time'],
                'temperatura_media': data['daily']['temperature_2m_mean'],
                'precipitacion': data['daily']['precipitation_sum'],
                'viento_max': data['daily']['windspeed_10m_max']
            })
            temp['origen'] = row['origen']
            clima_data.append(temp)
            print(f"OK: {row['origen']} ({i+1}/{len(airports_db)})")
        except Exception as e:
            print(f"Error con {row['origen']}: {e}")
        time.sleep(0.5)

    clima_data = pd.concat(clima_data, ignore_index=True)
    clima_data['fecha_vuelo'] = pd.to_datetime(clima_data['fecha_vuelo'])

    print(f"\nFilas de clima obtenidas: {len(clima_data)}")
    clima_data.head()

    print('Guardamos el csv de climas del año de cada aeropuerto...')
    clima_data.to_csv('clima_2022_por_aeropuerto.csv', index=False)
    print('Archivo guardado: clima_2022_por_aeropuerto.csv')

    return clima_data

In [11]:

if not os.path.exists('clima_2022_por_aeropuerto.csv'):
   print('El archivo clima_2022_por_aeropuerto.csv no existe. Comienza el llamado a la api para armar el csv...')
   clima_data = clima_por_aeropuerto()
else:
   print('El archivo clima_2022_por_aeropuerto.csv si existe.')
   clima_data = pd.read_csv('clima_2022_por_aeropuerto.csv')
   clima_data['fecha_vuelo'] = pd.to_datetime(clima_data['fecha_vuelo'])


print('clima_2022_por_aeropuerto.csv cargado!')

El archivo clima_2022_por_aeropuerto.csv si existe.
clima_2022_por_aeropuerto.csv cargado!

In [12]:
clima_data.head(4)

  fecha_vuelo  temperatura_media  precipitacion  viento_max origen
0  2022-01-01                2.7           11.7        36.6    ABQ
1  2022-01-02               -4.8            0.0        20.6    ABQ
2  2022-01-03               -2.3            0.0        10.5    ABQ
3  2022-01-04                0.7            0.0        10.4    ABQ

Hacemos el merge del clima con el df de 2022.

In [13]:
df_2022 = df_2022.merge(clima_data, on=['origen', 'fecha_vuelo'], how='left')

print(f"Filas después del merge: {len(df_2022)}")
print("Nulos en columnas de clima:")
print(df_2022[['temperatura_media', 'precipitacion', 'viento_max']].isnull().sum())

Filas después del merge: 154586
Nulos en columnas de clima:
temperatura_media    0
precipitacion        0
viento_max           0
dtype: int64

Nos quedamos solo con las columnas que son de antes del hecho generador, para evitar el leakage.

In [15]:
columnas_validas = [
    'fecha_vuelo', 'aerolinea', 'codigo_aerolinea', 'numero_vuelo',
    'origen', 'ciudad_origen', 'destino', 'ciudad_destino',
    'hora_salida_programada', 'hora_llegada_programada',
    'duracion_programada', 'distancia',
    'temperatura_media', 'precipitacion', 'viento_max'
]

df_modelo = df_2022[columnas_validas + ['retrasado']]

print(f"Filas finales en df_modelo: {len(df_modelo)}\n")
print('\n'.join(df_modelo.columns.tolist()))

Filas finales en df_modelo: 154586

fecha_vuelo
aerolinea
codigo_aerolinea
numero_vuelo
origen
ciudad_origen
destino
ciudad_destino
hora_salida_programada
hora_llegada_programada
duracion_programada
distancia
temperatura_media
precipitacion
viento_max
retrasado